### ISSUE TITLE
Question about angular 6

### ISSUE THREAD

**Issue by musso** [daikiojm/angular-aws-amplify#1]
Can update the example to angular 6 ?

**Comment by ghost** [comment]
Yes you can. Like that.
Angular Update Guide | 5.0 -> 6.0 for Basic Apps
Before Updating

Switch from HttpModule and the Http service to HttpClientModule and the HttpClient service. HttpClient simplifies the default ergonomics (You don't need to map to json anymore) and now supports typed return values and interceptors. Read more on angular.io

During the Update

Make sure you are using Node 8 or later


Update your Angular CLI globally and locally, and migrate the configuration to the new angular.json format by running the following:

npm install -g @angular/cli
npm install @angular/cli
ng update @angular/cli


Update all of your Angular framework packages to v6, and the correct version of RxJS and TypeScript.

ng update @angular/core

After the update, TypeScript and RxJS will more accurately flow types across your application, which may expose existing errors in your application's typings


Update Angular Material to the latest version.

ng update @angular/material

This will also automatically migrate deprecated APIs.


Use ng update or your normal package manager tools to identify and update other dependencies.

After the Update

Remove deprecated RxJS 6 features using rxjs-tslint auto update rules.

For most applications this will mean running the following two commands:

npm install -g rxjs-tslint
rxjs-5-to-6-migrate -p src/tsconfig.app.json


Once you and all of your dependencies have updated to RxJS 6, remove rxjs-compat.

**Comment by musso** [comment]
@rudyhadoux Thanks very much for the details on how to update from angular 5 to angular 6. I found that `aws-amplify` latest version got problem with angular 6 SSR due to the use of `localstorage` at server side. Has to downgrade to version  0.3.3 or lower for SSR

**Comment by ghost** [comment]
Interesting, do you have a link for that problem ?
I think you can close the issue.

**Comment by ghost** [comment]
Good news, it works with Angular 6 and AWS Amplify 1.
https://github.com/rudyhadoux/angular6awsamplify1

**Comment by musso** [comment]
@rudyhadoux Great that they released version 1. May I ask if it works in Server Service Rendering (SSR) Mode ? [https://github.com/rudyhadoux/angular6awsamplify1](https://github.com/rudyhadoux/angular6awsamplify1) isn't a SSR version. My experience is only aws-amplify v0.3.3 or lower works for SSR. I will close this first.

**Comment by ghost** [comment]
I do not know SSR. I use Angular 6 for front-end and Serverless for back-end.
With that, I can do anything.

**Comment by musso** [comment]
fyi [https://angular.io/guide/universal](https://angular.io/guide/universal), which is good for SEO

**Comment by ghost** [comment]
Other solutions exist.
I do not use Universal.
Google crawls Typescript web sites too.

**Comment by ghost** [comment]
Did you see that ?
Using Dependency Injection to implement Authentication
To handle authentication, this is one way to do it:

On the client we want the identity of the user to be taken from a token available either on a cookie or in the browser local storage.

on the server, while rendering the request we want the identity token to be read from an HTTP request header.

How to have the same page output while navigating to that page on the client via a router transition vs on the server via a browser refresh?

First define a Service interface
The first step is to define an interface that your service will provide, which is independent of the runtime:

export interface AuthenticationService {

    signUp(activationLink:boolean);
    login();
    logout();
    isLoggedIn();
    isLoggedInWithGitHub();

}

view raw04.ts hosted with ❤ by GitHub
Then we provide two implementations for this interface, one for the client and the other for the server. For example on the server there is no occasion for the login method being called, so we throw an error:

export class ServerAuthenticationService implements AuthenticationService {

    constructor(private authenticationId, private isUserLoggedIn:boolean) {
        
    }

    signUp() {
        throw new Error("Signup event cannot be called while doing server side rendering");
    }
    

    login() {
        throw new Error("Login event cannot be called while doing server side rendering");
    }

    logout() {
        throw new Error("Logout event cannot be called while doing server side rendering");
    }
    
    isLoggedIn() {
        return this.isUserLoggedIn;
    }

    isLoggedInWithGitHub() {
        ...
    }
}

view raw05.ts hosted with ❤ by GitHub
While on the client, we are going to trigger the Auth0 lock screen (a third-party browser only library) to provide a sign-in form:

@Injectable()
export class ClientAuthenticationService implements AuthenticationService {

    signUp(activationLink = false) {
        this.messagesService.clearAll();
        const lock = new Auth0Lock(AUTH0_API_KEY, AUTH0_SUB_DOMAIN);

        lock.showSignup(this.loginConfig(activationLink), this.loginCallback());
    }
    ....

}

view raw06.ts hosted with ❤ by GitHub
We then inject different implementations of the interface on the server and on the client, for the same injection token:

// define an injection name
export const authenticationService = new OpaqueToken("authenticationService");

// inject on the server
provide(authenticationService, {
    useFactory: () => new ServerAuthenticationService(req.authenticationId,isLoggedIn)
})
            
// inject on the client
provide(authenticationService, {
useFactory: (messagesService: MessagesService, ngZone: NgZone, cookieService: CookieService, userService: UserService, router:Router, gitHubService : GitHubService) => { 
    return new ClientAuthenticationService(messagesService, ngZone, cookieService, userService, router, gitHubService);
    },
  deps: [MessagesService, NgZone, CookieService, UserService, Router, GitHubService]
  })])

view raw07.ts hosted with ❤ by GitHub
And this is how we can do something different on the client and on the server in Angular Universal, by leveraging the Angular dependency injection container.
